# Embeds a set of files into one generated C++ translation unit, so the binary
# carries them and needs nothing beside it on disk. This is what lets wowee.exe
# be dropped next to the original game executable with no assets/ directory
# copied along with it.
#
# Run as a script (cmake -P), twice over the life of a build tree:
#
#   * once at configure time, so the generated sources exist before anything
#     tries to compile them, and
#   * from a build-time custom command whose DEPENDS are the files being
#     embedded, so recompiling a shader regenerates the table.
#
# Expects: SRC_DIR   directory to read files from
#          PATTERN   glob within SRC_DIR (e.g. "*.spv")
#          PREFIX    prepended to each file's name to form its lookup key,
#                    which is what the C++ call sites already spell
#          OUT_CPP   generated translation unit
#          OUT_HPP   generated header declaring the lookup

if(NOT DEFINED PATTERN)
    set(PATTERN "*")
endif()
if(NOT DEFINED PREFIX)
    set(PREFIX "")
endif()

file(GLOB EMBED_FILES "${SRC_DIR}/${PATTERN}")
# Sorted, so the generated file is byte-identical across machines and a
# re-run that changed nothing does not rewrite it (see copy_if_different
# at the end, which is what keeps a no-op run from rebuilding the world).
list(SORT EMBED_FILES)

# The header is fixed text - it declares the lookup, it does not depend on what
# was found. Written every run all the same, so a build tree that lost it
# gets it back.
file(WRITE "${OUT_HPP}.tmp"
"// Generated by cmake/EmbedResources.cmake - do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace wowee {
namespace generated {

/// One embedded file: the path callers name it by, and its contents.
///
/// Words rather than bytes because vkCreateShaderModule wants a const
/// uint32_t*, and a uint32_t array is aligned for that by construction - a
/// byte array would have to be copied somewhere aligned before it could be
/// used. sizeBytes is what Vulkan calls codeSize.
struct EmbeddedResource {
    const char* path;
    const uint32_t* words;
    size_t sizeBytes;
};

/// The table. Returns nullptr with count 0 when nothing was embedded - a tree
/// with no compiled shaders in it still builds, and the filesystem is then the
/// only place a shader can come from.
const EmbeddedResource* embeddedShaders(size_t& count);

} // namespace generated
} // namespace wowee
")

file(WRITE "${OUT_CPP}.tmp"
"// Generated by cmake/EmbedResources.cmake - do not edit.
#include \"rendering/embedded_shaders.hpp\"

namespace wowee {
namespace generated {
namespace {

")

set(EMBED_ENTRIES "")
set(EMBED_INDEX 0)

foreach(EMBED_FILE ${EMBED_FILES})
    get_filename_component(EMBED_NAME "${EMBED_FILE}" NAME)

    file(READ "${EMBED_FILE}" EMBED_HEX HEX)
    string(LENGTH "${EMBED_HEX}" EMBED_HEX_LEN)
    math(EXPR EMBED_SIZE "${EMBED_HEX_LEN} / 2")

    # SPIR-V is a stream of 32-bit words. Anything that is not a whole number
    # of them is not a module this table can hand to Vulkan, so leave it out
    # rather than emit an array the loader would reject at runtime.
    math(EXPR EMBED_REMAINDER "${EMBED_HEX_LEN} % 8")
    if(NOT EMBED_SIZE GREATER 0 OR NOT EMBED_REMAINDER EQUAL 0)
        message(WARNING "EmbedResources: skipping ${EMBED_NAME}, ${EMBED_SIZE} bytes is not a whole number of 32-bit words")
        continue()
    endif()

    # Little-endian: four hex bytes aa bb cc dd become the word 0xddccbbaa.
    # Assembling the words here rather than at load time is what keeps the
    # array a uint32_t array.
    string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1," EMBED_WORDS "${EMBED_HEX}")
    # Eight words to a line. CMake's regex has no {n} repetition, hence the
    # eight spelled-out groups; \\1 is the whole run of them.
    string(REGEX REPLACE
        "((0x........,)(0x........,)(0x........,)(0x........,)(0x........,)(0x........,)(0x........,)(0x........,))"
        "\\1\n    " EMBED_WORDS "${EMBED_WORDS}")

    file(APPEND "${OUT_CPP}.tmp"
"// ${PREFIX}${EMBED_NAME} (${EMBED_SIZE} bytes)
const uint32_t kResource${EMBED_INDEX}[] = {
    ${EMBED_WORDS}
};

")

    list(APPEND EMBED_ENTRIES
         "    {\"${PREFIX}${EMBED_NAME}\", kResource${EMBED_INDEX}, ${EMBED_SIZE}},")
    math(EXPR EMBED_INDEX "${EMBED_INDEX} + 1")
endforeach()

if(EMBED_ENTRIES)
    string(REPLACE ";" "\n" EMBED_TABLE "${EMBED_ENTRIES}")
    file(APPEND "${OUT_CPP}.tmp"
"const EmbeddedResource kTable[] = {
${EMBED_TABLE}
};

} // namespace

const EmbeddedResource* embeddedShaders(size_t& count) {
    count = sizeof(kTable) / sizeof(kTable[0]);
    return kTable;
}

} // namespace generated
} // namespace wowee
")
else()
    # No files to embed. A zero-length array is not valid C++, so say nothing
    # rather than declare one.
    file(APPEND "${OUT_CPP}.tmp"
"} // namespace

const EmbeddedResource* embeddedShaders(size_t& count) {
    count = 0;
    return nullptr;
}

} // namespace generated
} // namespace wowee
")
endif()

# Only touch the real files when their contents changed. Rewriting a megabyte
# of byte arrays on every build would recompile this translation unit, and
# relink, for nothing.
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${OUT_HPP}.tmp" "${OUT_HPP}")
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${OUT_CPP}.tmp" "${OUT_CPP}")
file(REMOVE "${OUT_HPP}.tmp" "${OUT_CPP}.tmp")

message(STATUS "EmbedResources: embedded ${EMBED_INDEX} file(s) from ${SRC_DIR}")
